import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useEffect, useState } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "../components/Weather";
import Spinner from "../components/Spinner";
import { FaExchangeAlt } from "react-icons/fa";

export default function Home() {
	const [city, setCity] = useState("");
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);
	const [units, setUnits] = useState("metric");

	const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=${units}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

	const fetchWeather = (e) => {
		e.preventDefault();
		setLoading(true);
		axios.get(url).then((response) => {
			setWeather(response.data);
		});
		setCity("");
		setLoading(false);
	};

	const changeUnits = () => {
		if (units === "metric") {
			setUnits("imperial");
		}
		console.log(units);
	};

	if (loading) {
		return <Spinner />;
	} else {
		return (
			<div>
				<Head>
					<title>Weather - Next App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='./favicon.ico' />
				</Head>

				{/*Overlay*/}
				<div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'></div>

				{/*Background*/}
				<Image
					alt='/'
					className=' object-cover'
					src='https://images.unsplash.com/photo-1592210454359-9043f067919b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1920&q=1080'
					layout='fill'
				/>

				{/*Search*/}
				<div className='relative flex flex-col justify-end gap-5 px-3 items-center w-full h-[20vh] pt-4 text-white z-10'>
					<form
						onSubmit={fetchWeather}
						className='flex justify-between items-center w-full max-w-[450px] sm:p-3 px-3 py-1 mx-auto bg-transparent border border-gray-300 text-white rounded-2xl'>
						<div>
							<input
								onChange={(e) => setCity(e.target.value)}
								className='bg-transparent border-none text-white w-full  focus:outline-none text-lg  sm:text-2xl placeholder:text-gray-300'
								type='text'
								placeholder='Search city'
							/>
						</div>
						<button onClick={fetchWeather}>
							<BsSearch size={20} />
						</button>
					</form>

					<div
						className='items-center z-20 flex cursor-pointer text-center'
						onClick={() => changeUnits()}>
						<h2 className='mr-4 font-semibold '>
							Change to {units === "metric" ? "Fahrenheit" : "Celsius"}
						</h2>
						<FaExchangeAlt size={25} />
					</div>
				</div>

				{/*Weather*/}
				{weather.main && <Weather data={weather} units={units} />}
			</div>
		);
	}
}
